# -*- coding: utf-8 -*-
"""Hangman.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14zkD7G0-NwmcACcUQHkiPAPslOuXRI40

# Hangman Game
"""

import os
import requests

"""# Quick clear function

Find out how the underscore works here
"""

def clear():
 
    # for windows
    if os.name == 'nt':
        _ = os.system('cls')
 
    # for mac and linux(here, os.name is 'posix')
    else:
        _ = os.system('clear')

"""# The drawScreen function draws the hangman and the blank spaces"""

def drawScreen(
    wordLength, 
    guesses
):

    gallows = ["",
               "----|",
               "----|\n|\n|\n|\n|\n|", 
               "----|\n|   |\n|\n|\n|\n|", 
               "----|\n|   |\n|   O\n|\n|\n|", 
               "----|\n|   |\n|   O\n|  /\n|\n|", 
               "----|\n|   |\n|   O\n|  /|\n|\n|", 
               "----|\n|   |\n|   O\n|  /|\\\n|\n|",
               "----|\n|   |\n|   O\n|  /|\\\n|   |\n|",
               "----|\n|   |\n|   O\n|  /|\\\n|   |\n|  /",
               "----|\n|   |\n|   O\n|  /|\\\n|   |\n|  / \\"
              ]

    clear()

    print(gallows[guesses])
    print("\n")

    for i in range(len(answer)):
        print(answer[i], end = ' ')
    
    print("\n")

"""# The checkGuess function checks to see if the letter Player 2 guessed is in the word

If it is, it returns True, if not, it returns False
"""

def checkGuess(guess, word):

    rightwrong = False

    for letter in range(len(word)):
        if guess == word[letter]:
            answer[letter] = guess
            rightwrong = True
            
    return rightwrong

"""# Gets the word from Player 1 or api"""

print("One player or two? (enter '1' or '2')")
players = input()

if int(players) == 1:
    print("Player 1! Enter your word. (No peaking, player 2!)\n")
    word = input()
else:
    URL = "https://random-word-api.herokuapp.com/word"
    response = requests.get(url = URL)
    word = response.text[2:len(response.text)-2]

clear()

answer = []

for l in range(len(word)):
    answer.append("_")

"""# Now the game loop begins"""

guesses = 0

while guesses < 10:
    drawScreen(len(word), guesses)
    
    print("Guess a letter: ")
    guess = input()

    guesses += 1

    if checkGuess(guess, word):
        guesses = guesses - 1

    if not "_" in answer:
        drawScreen(len(word), guesses)
        print("You won!!!")
        break

if guesses == 10:
    drawScreen(len(word), guesses)
    print("You lose.")
    print("The word was " + word)